name: Java Get.java CI

on: [ push ]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'
    - name: Print Java version
      run: java --version
    - name: Get JUnit 3.7 JAR from Maven Central
      run: java -Debug=true demo/main/Get.java https://repo1.maven.org/maven2/junit/junit/3.7/junit-3.7.jar
    - name: Get same JAR, again
      run: java -Debug=true demo/main/Get.java https://repo1.maven.org/maven2/junit/junit/3.7/junit-3.7.jar
